
export const countries = [
  { value: 'ae', label: 'الإمارات العربية المتحدة' },
  { value: 'jo', label: 'الأردن' },
  { value: 'bh', label: 'البحرين' },
  { value: 'dz', label: 'الجزائر' },
  { value: 'sa', label: 'السعودية' },
  { value: 'sd', label: 'السودان' },
  { value: 'so', label: 'الصومال' },
  { value: 'iq', label: 'العراق' },
  { value: 'kw', label: 'الكويت' },
  { value: 'ma', label: 'المغرب' },
  { value: 'ye', label: 'اليمن' },
  { value: 'tn', label: 'تونس' },
  { value: 'qa', label: 'قطر' },
  { value: 'lb', label: 'لبنان' },
  { value: 'ly', label: 'ليبيا' },
  { value: 'eg', label: 'مصر' },
  { value: 'mr', label: 'موريتانيا' },
  { value: 'om', label: 'عمان' },
  { value: 'ps', label: 'فلسطين' },
  { value: 'sy', label: 'سوريا' },
  // Add more countries in Arabic alphabetical order
  { value: 'af', label: 'أفغانستان' },
  { value: 'al', label: 'ألبانيا' },
  { value: 'de', label: 'ألمانيا' },
  { value: 'id', label: 'إندونيسيا' },
  { value: 'ir', label: 'إيران' },
  { value: 'it', label: 'إيطاليا' },
  { value: 'pk', label: 'باكستان' },
  { value: 'br', label: 'البرازيل' },
  { value: 'pt', label: 'البرتغال' },
  { value: 'be', label: 'بلجيكا' },
  { value: 'bd', label: 'بنغلاديش' },
  { value: 'tr', label: 'تركيا' },
  { value: 'dk', label: 'الدنمارك' },
  { value: 'ru', label: 'روسيا' },
  { value: 'sg', label: 'سنغافورة' },
  { value: 'se', label: 'السويد' },
  { value: 'ch', label: 'سويسرا' },
  { value: 'cn', label: 'الصين' },
  { value: 'fr', label: 'فرنسا' },
  { value: 'my', label: 'ماليزيا' },
  { value: 'gb', label: 'المملكة المتحدة' },
  { value: 'us', label: 'الولايات المتحدة الأمريكية' },
  { value: 'jp', label: 'اليابان' },
  { value: 'in', label: 'الهند' },
  // Continue with other countries...
];
