// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqmpfnjiunjqwyppscad.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxbXBmbmppdW5qcXd5cHBzY2FkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMDI1MzksImV4cCI6MjA2MDY3ODUzOX0.C9HNymy6S9cp1Fd36SdKRufN_RduTuCt2f95dGGowgg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);